### ISSUE TITLE
Chromatic aberration removal possible?

### ISSUE THREAD

**Issue by k9bbzJavftZaqAqSW3dY** [gurrgur/er-patcher#1]
Hi, fantastic tool. Very educational too, might do this with other hex-editable games as well!
Only thing that is left to fix after the replacements you made would be the chromatic aberration. I have no idea how the entire game industry is so obsessed with it but bad camera lenses don't make the graphics more realistic. ^^

**Comment by gurrgur** [comment]
Hey, thanks. I just added a ca removal toggle ;) Please let me know if you notice any issues with it.
