### ISSUE TITLE
Skip Bandai Namco and From Software logos

### ISSUE THREAD

**Issue by GrzegorzKozub** [gurrgur/er-patcher#11]
Do you think we could add a feature to skip Bandai Namco and From Software logos? There's already a DLL-based mod [DarkSouls3RemoveIntroScreens](https://github.com/bladecoding/DarkSouls3RemoveIntroScreens) that does that and maybe we could use it for inspiration. The patching code seems to be in [this CPP file](https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/blob/master/SoulsSkipIntroScreen/dllmain.cpp).

**Comment by gurrgur** [comment]
Hi, that's a good idea. Personally I don't mind the intro logos since they are skippable and don't take too long to finish. Because of that I won't be working on this myself, buf if someone finds a way to port the patches from the code you linked I'll add it.

**Comment by fabienengels** [comment]
That would be nice to be able to skip them, at least on my machine, I'm not able to skip them like @GrzegorzKozub :)

**Comment by gurrgur** [comment]
Please check out the newest release in which I added an option for this :)
