### ISSUE TITLE
Worse performance with the Ultrawide fix option

### ISSUE THREAD

**Issue by Khrona98** [gurrgur/er-patcher#14]
Hello there!

From what I saw on reddit when Elden Ring launched was that the game had proper ultrawide built-in but the game overlays it with black bars. There are posts about it like [this one](https://www.reddit.com/r/Eldenring/comments/t2va45/i_unlocked_ultrawide_by_accident/) or [this one](https://www.reddit.com/r/ultrawidemasterrace/comments/tkrn9k/elden_ring_glitched_and_let_me_see_native_219/) for example.

That would mean that the game is already rendering the extra space but simply refusing to show it to the player. If that is true, then removing the black bars should not decrease performance, but from my own testing this is not the case as I see performance degradation from 5-10 FPS when removing the black bars. I couldn't find other people reporting the same issue, so I decided to test it.

<details>
  <summary>Screenshots</summary>
  
  This was taken on the Windmills area, and there is a **5 FPS** decrease overall:
  
![Screenshot_20220323_202459](https://user-images.githubusercontent.com/9277125/159818103-4f91081c-8032-4b3a-b460-2c08dad9acb4.png)

![Screenshot_20220323_202300](https://user-images.githubusercontent.com/9277125/159818128-b5aec7ff-cf24-4502-8c30-295a42f5ec05.png)
  
</details>

This also seems to happen on Liurnia of the Lakes, where I get **50-60 FPS**, mostly **55**, **without** the patcher and **40-50 FPS**, mostly **45**, **with** the patcher. This wouldn't be much of a problem in itself but I can really feel the difference, probably because the lowest Freesync range of my monitor is 45 Hz and the game gets choppy around that framerate.

I did the testing with only the ultrawide option, without it but with the patcher to start offline, without the patcher completely and with only the following options: `-uvasf`, the results were consistent throughout. Unlocking the framerate also made no difference.

I can't test with other patchers like Flawless Widscreen since I don't have a windows installation on this computer, so, my question here is: is this is supposed to happen? And if not, can it be fixed in this patcher somehow? Or is it an issue with the game itself?

**Comment by Khrona98** [comment]
Yeah I did test it out before but I decided to do it again since Proton Experimental got an update, but the results are the same, `./er-patcher -uvasf -- %command%` gives performance penalty and either no `er-patcher` or `./er-patcher -vasf -- %command%` gives me base performance.

I don't have access to a newer Mesa release so I can't be sure if any improvements there would change anything. I'll try on another distro with newer Mesa and report back, feel free to close this issue if you see fit tho.

**Comment by gurrgur** [comment]
Mesa 22 might help. For me it gave a boost of ~15% over 21.3.7 with an RX570. With 21.3.7 the gpu load shown in mangohud was around 85-90% whereas with mesa 22 it's basically a flat 100%.

Anyway, since this doesn't seem to be an issue with out patch, I'll close this issue.

**Comment by Khrona98** [comment]
Just as a final update in case anyone stumbles upon this issue:

Instead of trying on another distro I locally built mesa 22.0.0 and tried it on Elden Ring. Without compiling mesa-32bit, EAC won't open and the game refuses to work, but using er-patcher lets the game open and the difference is stark. I now manage to get 60-75 FPS on Liurnia alone from my small testing.

So yeah if anyone happens to have performance issues on Ultrawide in Elden Ring on an AMD GPU, Mesa 22.0.0 and up will have you covered.
