### ISSUE TITLE
Issues on Steam Deck

### ISSUE THREAD

**Issue by n00mkrad** [gurrgur/er-patcher#20]
Running via Game Mode does not do anything, game won't launch.

If I try `konsole -e python -i er-patcher --all -- %command%` on Desktop Mode, I get the following:

```
/run/media/mmcblk0p1/WindowsGames/ELDENRING/Game/er-patcher:133: DeprecationWarning: pathlib.Path.link_to() is deprecated and is scheduled for removal in Python 3.12. Use pathlib.Path.hardlink_to() instead.
  f.link_to(game_dir_patched / f)
Traceback (most recent call last):
  File "/run/media/mmcblk0p1/WindowsGames/ELDENRING/Game/er-patcher", line 138, in <module>
    subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/run/media/mmcblk0p1/WindowsGames/ELDENRING/Game/er-patcher-tmp/eldenring.exe')

```

Maybe I need to do chmod?

**Comment by gurrgur** [comment]
Hey, 

are you running this from within steam or directly from a terminal?

I'm asking because the error is the same as one from a comment on another issue https://github.com/gurrgur/er-patcher/issues/3#issuecomment-1079392040. The error occurred occurs because the proton part is missing from the launch command so the script tries to launch "eldenring.exe" directly. This fails of course because "eldenring.exe" is not marked as executable.

**Comment by n00mkrad** [comment]
I'll try with Steam. But not sure if I can get a console output that way.

**Comment by gurrgur** [comment]
That's what the `konsole -e` part is for. It spawns a terminal window so you can see what the program prints out. Thy `-i` flag for python enables interactive mode so the window won't close after the crash.

**Comment by n00mkrad** [comment]
> That's what the `konsole -e` part is for. It spawns a terminal window so you can see what the program prints out. The `-i` flag for python enables interactive mode so the window won't close in case the patcher crashes or the game stops running.

But konsole is a native Linux application, I can't use Proton with that, right?

**Comment by gurrgur** [comment]
It will work, at least when you run steam in desktop mode. The reason is that proton is run within konsole and not the other way round ;)

**Comment by n00mkrad** [comment]
```
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/python: can't open file '/home/deck/.local/share/Steam/er-patcher': [Errno 2] No such file or directory
```

Well I need an absolute path here, one sec

**Comment by gurrgur** [comment]
Are you running Elden Ring from steam with the launch options above when you get that output? When running the game, absolute paths shouldn't be needed. On a regular desktop automatically sets the working dir to the "Game" folder.

**Comment by n00mkrad** [comment]
> Are you running Elden Ring from steam with the launch options above when you get that output? When doing that, absolute paths shouldn't be needed. On a regular desktop steam automatically sets the working dir to the "Game" folder.

Well I'm starting Konsole from Steam, let me try using that in the ER launch opts

**Comment by n00mkrad** [comment]
That works. Let my try Desktop Mode but without the konsole/python args

**Comment by n00mkrad** [comment]
Yep - to recap:

`konsole -e python -i er-patcher --all -- %command%` **WORKS**

`./er-patcher --all -- %command%` **DOES NOT WORK**

**Comment by gurrgur** [comment]
Does `python er-patcher --all -- %command%` work in deck mode?
The problem might be caused by the python shebang not working for some reason.

**Comment by n00mkrad** [comment]
> Does `python er-patcher --all -- %command%` work in deck mode? The problem might be caused by the python shebang not working for some reason.
> 
> Edit: Or it could be caused by missing execution permissions in which case running `chmod +x er-patcher` once would do the trick (not as launch option, just spawn a terminal in the game directory).

It is a bit buggy in Game Mode because Gamescope keeps switching between the Konsole and ER windows (optimally for Game Mode there should only be a single window) but it seems like it stops glitching once the main menu has loaded. So yeah that works.

**Comment by gurrgur** [comment]
Try this one, it should behave like the one which spawns konsole except it doesn't spawn konsole: `python er-patcher --all -- %command%`.
I just removed the `konsole -e` part and the `-i` flag for python.

**Comment by n00mkrad** [comment]
Okay, doing `chmod +x er-patcher` seems to have worked!

It now runs fine in Game Mode without konsole using `./er-patcher --all -- %command%`

> Try this one, it should behave like the one which spawns konsole except it doesn't spawn konsole:
> 
> > `python er-patcher --all -- %command%`
> 
> I just removed the `konsole -e` part and the `-i` flag for python.

This also works. Might be the preferred method for most people since this avoids having to chmod anything and works completely in Game Mode as long as the files are installed.

**Comment by gurrgur** [comment]
Alright cool and thanks for helping debug this! I'll update the readme and replace all mentions of "./er-patcher" with "python er-patcher". I suppose we can close this issue then :)

**Comment by n00mkrad** [comment]
Thanks for the support and this patcher! Makes for a great experience on the Deck.
