### ISSUE TITLE
update for version 1.04 seems to have broken ultrawide

### ISSUE THREAD

**Issue by ginjiruu** [gurrgur/er-patcher#24]
all other flags seem to work but widescreen no longer functions

**Comment by AndreaVentitre** [comment]
Hi, also 
--increase-animation-distance 
doesn't seem to work after 1.4 : (.

**Comment by joao-pedro-braz** [comment]
Hello!

I have a fix available and already opened a PR. Until it is fixed you could use the er-patcher from [my fork](https://github.com/joao-pedro-braz/er-patcher/tree/main).

Best Regards,
João Pedro Braz
