### ISSUE TITLE
Ultrawide option seems to not work.

### ISSUE THREAD

**Issue by squeak5476** [gurrgur/er-patcher#38]
Ultrawide seems to not work on my end, possible due to my odd resolution.
3840x1200.

Fedora 36.

**Comment by squeak5476** [comment]
Yeah all other options work without issue, but not the ultrawide.
![unknown-1.png](https://user-images.githubusercontent.com/39633223/182218219-8fb14acf-2d51-466d-b1e0-9956d5ace7c0.png)

**Comment by gurrgur** [comment]
Please double check the correct resoltion is set in game options. If you have a 16 by 9 res set, then of course there will be black bars.

If you aren't using current patch, you can try older patcher releases which are labeled with the game version they are compatible with.

The unusual resolution _shouldn't_ cause this but you can never know, so if the above dont solve the problem, as mentioned before you can try forcing a less wide resolution using gamescope. 21:9 is the widest I have tested myself but I have heard people using super ultrawide monitors with this without any issue

**Comment by squeak5476** [comment]
Latest patch, 100% using my resolution. I guess I'll try gamescope.
