### ISSUE TITLE
Ultra wide not working on 1.06

### ISSUE THREAD

**Issue by NewOxygen91** [gurrgur/er-patcher#39]
For reference I'm on the steam deck. Other codes such as rate limiter works fine but the ultra wide option does not remove the black bars on the latest elden ring patch.

**Comment by gurrgur** [comment]
Ultrawide is still working fine for me on 1.06 so I am sceptical that this issue is caused by the ultrawide patch not working. Perhaps the wrong resolution is set ingame?

**Comment by mikeyd85** [comment]
Confirming that ultrawide is still working on 1.06.
