### ISSUE TITLE
tagged release for the latest revision doesn't exist

### ISSUE THREAD

**Issue by IvarWithoutBones** [gurrgur/er-patcher#40]
Hello, I saw that commit c3ee974b54f28e4044926cf1b551d103099df905 fixes ultrawide support on 1.05 (and 1.06 from my testing), but there currently isn't a tagged release including that revision.

I'm asking because i maintain the [er-patcher package](https://github.com/NixOS/nixpkgs/blob/20ef7ba6ebbc0ba119e24a8eceeab9ff037d9d39/pkgs/tools/games/er-patcher/default.nix) in nixpkgs, where we prefer to use releases rather than git revisions. Our package currently doesn't have ultrawide support on the latest version of the game.

**Comment by gurrgur** [comment]
Thanks for the reminder, somehow I never got around to it. Anyway, I published a new release which includes the most recent compatibility updates :)

**Comment by IvarWithoutBones** [comment]
Thanks, our packaged has been updated with https://github.com/NixOS/nixpkgs/pull/189249 :)
