### ISSUE TITLE
Can't move in game

### ISSUE THREAD

**Issue by gdiazbanuelos** [gurrgur/er-patcher#5]
Patcher launches correctly with mods (ultrawide fix, etc...), but once in game I can only rotate. I can interact with menus like pressing start and use the menu but I can not move.

I have tried moving with a controller and with a keyboard, on both I can only rotate my character and nothing else.

Any ideas what is going on? I launched back into Windows and everything is fine, it only happens on my Linux partition and I try running the game with this patcher.

Thank you!

**Comment by gurrgur** [comment]
Try launching with 
1. `./er-patcher -- %command%` If this causes the problem, skip 2.
2. Every other option you're using one at a time and see which causes the problem (like `./er-patcher -u -- %command%`)

Additional system info would be helpful, e.g.
- game version
- distro
- graphics card

**Comment by gdiazbanuelos** [comment]
I tried it with only `./er-patcher -- %command%`, and I still had the same issue.

Game version: 1.02.3

Proton version: I have tried Valve's Proton Experimental, 7.0-1, and GE-Proton7-9

Distro: Manjaro 21.2.4

GPU: NVIDIA RTX 3090

**Comment by gdiazbanuelos** [comment]
I tried launching the game with `./er-patcher -- env VKD3D_CONFIG=skip_application_workarounds %command%` and I had the same issue.

I followed the steps [here](https://github.com/gurrgur/er-patcher/issues/3#issuecomment-1063903203) and the patch worked but I still can't move.

**Comment by gurrgur** [comment]
That's weird and I don't know what could be causing it, but it seems like none of the patches is the problem. I remember having a similar issue with Dark Souls 3 (though without any hacks). IIRC back then it was fixed by a proton update.

I assumed before that the game works fine on linux when not using er-patcher, am I correct?

**Comment by gdiazbanuelos** [comment]
The game works fine without the patcher. I can use my controller but lose the ultrawide feature.

Even without the patcher, I still need to bypass EAC or I get a white screen. It seems until Proton gets fixed, I can just use Windows until then. Awesome patch tho!

**Comment by gdiazbanuelos** [comment]
I uninstalled Elden Ring and tried the patcher again. It works now! I can move! I have no clue what happened!
