### ISSUE TITLE
ultrawide suddenly stopped working?

### ISSUE THREAD

**Issue by YAPPYawesome** [gurrgur/er-patcher#57]
I play on Steam Deck and this was working perfectly fine yesterday but then today when I launched the game it had the black bars again. The intro skip still works though. This is very confusing as I didn't even touch anything after I got it to work. I use python er-patcher -us -- %command% in the properties. When I launched it today and it broke I tried  running it without er-patcher then running it with it and that didn't work. I tried using --all instead but that didn't work either. Then I tried reinstalling er-patcher but that didn't work either.

**Comment by gurrgur** [comment]
So the game still runs when using `er-patches` and only the ultrawide patch is not working properly? That is strange indeed.
The patch should still work as of Elden Ring v1.10, so something else is not right.

Did you check the correct resolution is set in Elden Ring? Other than that I'm not sure what could be causing it.

**Comment by YAPPYawesome** [comment]
The resolution was the problem. I feel silly now that I didn’t even consider that.
