### ISSUE TITLE
FOV Support

### ISSUE THREAD

**Issue by zedseven** [gurrgur/er-patcher#6]
Would it be possible to support different FOV values?

From a cursory search around it seems like Flawless Widescreen supports changing the FOV.

It would be really nice to have an option like `--fov value` if doable.

Thank you for the great tool!

**Comment by gurrgur** [comment]
Hi, I had a look how the FOV patch works in Flawless Widescreen and unfortunately the method they use is not straight forward to implement in er-patcher. They patch the game memory at runtime and essentially inject _additional_ code whereas `er-patcher` in its current state can only _modiify_ existing code. So unless someone figures out to adjust the fov without having to inject additional code/instructions, you have to make do without or just use FWS.

**Comment by zedseven** [comment]
Ah, I didn't realise it injected additional code.
No problem, thank you for looking into it! I'll close this issue for now.
