### ISSUE TITLE
Game fails to open with Seamless Coop

### ISSUE THREAD

**Issue by R4ng3x** [gurrgur/er-patcher#61]
Opening the game with the normal launcher works perfectly, but opening it with Seamless Co-op opens the cmd and the game pretends to open but closes instantly.

I am playing on Windows 11 with the game on the latest version and Seamless Co-op on v1.5.1.

**Comment by Juppstein** [comment]
Same here with er-patcher and the latest seamless-coop 1.7.6 running on Linux Steam/Proton Experimental
