### ISSUE TITLE
The new dlc patch appears to break framerate unlock.

### ISSUE THREAD

**Issue by Rastafaustian** [gurrgur/er-patcher#66]
Arch Linux with Proton Experiemental: python er-patcher --rate 120 -sva -- %command%

I can confirm that the intros are still being skipped, but the frame rate is locked at 60.

**Comment by GosuDRM** [comment]
Can confirm.

**Comment by polsrepo** [comment]
Hello,
Check my pull request to fix the issue in your end until the author approves it:
https://github.com/gurrgur/er-patcher/pull/65/commits/a388b09bee51f547a51fdb2640a1fa25ee1061b1

**Comment by Rastafaustian** [comment]
> Hello, Check my pull request to fix the issue on your end if you don't want to wait for the author to approve it: #65

I just did, and was about to post here about the fix :)

I'm pretty new to git, but what worked for me is simply copy/paste  lines 40 and 107 into the existing file. Works like a charm. 

BTW, is there a way I'm missing to simply download the edited version of the file?

**Comment by gurrgur** [comment]
Thanks to @polsrepo for fixing this!

**Comment by HirschBerge** [comment]
Now that DLC has actually dropped, this is broken again. Still locked at 60

**Comment by gurrgur** [comment]
Reopening for now. I just tested it on the latest patch and it's working fine. Though I don't have the DLC to test with.

I'd appreciate people with DLC reporting back on this.

**Comment by HirschBerge** [comment]
Apologies for a bad report. I wget'd down the updated version in "/path/to/ELDEN RING" instead of "/path/to/ELDEN RING/Game"
ID10T error

**Comment by JohnnyJapes** [comment]
I just booted the DLC and walked into the first DLC area. Framerate patch appears to be working. 
`python er-patcher -r 144  -- %command%`
