### ISSUE TITLE
Crash on death with --disable-rune-loss

### ISSUE THREAD

**Issue by mettelden** [gurrgur/er-patcher#68]
With the new update of the game when you are killed the game crashes if --disable-rune-loss is present but if I remove it the game doesn't crash, I have also already tried the latest release of er-patcher

**Comment by MattiaDiChiara** [comment]
@gurrgur

**Comment by A1RM4X** [comment]
Can confirm. Game goes into boot loop / crash when die if option --disable-rune-loss is ON

**Comment by polsrepo** [comment]
Hello,
Try using my pr, see if it works!
https://github.com/gurrgur/er-patcher/pull/70

**Comment by polsrepo** [comment]
Hello,
Please check this pr, it might fix the crash
https://github.com/gurrgur/er-patcher/pull/71

**Comment by MattiaDiChiara** [comment]
@polsrepo someone has to merge it and relase.. so we can download it

**Comment by polsrepo** [comment]
> @polsrepo someone has to merge it and release.. so we can download it

you can just edit your er-patcher with my changes too :)

**Comment by A1RM4X** [comment]
@polsrepo @gurrgur Tested the PR. Working on my end.

**Comment by Ricecake35229294** [comment]
> > @polsrepo someone has to merge it and release.. so we can download it
> 
> you can just edit your er-patcher with my changes too :)

Thank you. It works for me

**Comment by gurrgur** [comment]
Thanks again to @polsrepo for fixing this and to everyone testing as well!
