### ISSUE TITLE
Fails to launch on Linux

### ISSUE THREAD

**Issue by nickolaij** [gurrgur/er-patcher#72]
I have a fairly fresh installation of PopOS - and the game works fine without the patcher.

Putting the following into my launch options (following the suggestions from #20):
`konsole -e python3 -i er-patcher --all -- %command%`

I get:
`ERROR: ld.so: object '/home/nick/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Traceback (most recent call last):
  File "/home/nick/.local/share/Steam/steamapps/common/ELDEN RING/Game/er-patcher", line 132, in <module>
    (game_dir_patched / d).mkdir(parents=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: 'er-patcher-tmp/er-patcher-tmp/er-patcher-tmp/er-patcher-tmp'
`

Any ideas?

**Comment by spookyghostlad** [comment]
I am also on PopOS and am running into the same issue, but I found that running the game with the command:
 ./er-patcher --all -- %command%

Seems to work for me, hope that works for you too.

**Comment by nickolaij** [comment]
Thank you so much! I had to do a little bit of extra work - just detailing it for anyone else:

1. In steam, set the launch options to: `./er-patcher --all -- %command%` or whatever you need.
2. In the game folder, I deleted the folder `er-patcher-tmp` -  I assume it got in some weird state from messing around.
3. Launch game :)
