### ISSUE TITLE
HDR through Gamescope @165 refresh rate and no black bars command

### ISSUE THREAD

**Issue by Bookingyo** [gurrgur/er-patcher#75]
For those looking to enable HDR with the er-patcher here is the command working for me in KDE 6.1 (Bazzite).

`ENABLE_GAMESCOPE_WSI=1 DXVK_HDR=1 gamescope -W 3440 -H 1440 -f -r 165 --hdr-enabled -- python er-patcher --all --rate 165 -- %command%`

@gurrgur not sure if you want to add this to the home page for those looking for this solution.

**Comment by gurrgur** [comment]
Thanks, I added it to the readme :)

**Comment by kzdixon** [comment]
I was going to attempt using gamescope for nightreign (likely unsupported, I know, but er-patcher when adjusted to point at its .exe works fine for launching seamless coop on Linux), but I am running into an issue where the game exits immediately if gamescope is used at all.

My launch args when attempting to use gamescope are:
```WINEDLLOVERRIDES="dinput8.dll=n,b" gamescope -w 3840 -h 2160 -r 144 -- python er-patcher --executable nrsc_launcher.exe -- %command%```

Without gamescope (working fine):
```WINEDLLOVERRIDES="dinput8.dll=n,b" python er-patcher --executable nrsc_launcher.exe -- mangohud gamemoderun %command%```

Just reporting in case there's a known issue with gamescope currently or not (am on 3.16.2).
