### ISSUE TITLE
Python=3.9 required for Windows

### ISSUE THREAD

**Issue by Meridolian** [gurrgur/er-patcher#8]
Hi ! 

I tried it on Ubuntu and it works so nice, thank you man ! 
But I also tried to run it in windows and i catch the exception " module 'argparse' has no attribute 'BooleanOptionalAction' ".
It seems like BooleanOptionalAction is only available from python 3.9.

**Comment by gurrgur** [comment]
Hi, added a note to the readme which clarifies the required python version. Unfortunately I have no intention of supporting older versions of python, so I'm closing this issue.

**Comment by Meridolian** [comment]
Hi, yeah no problem, 3.9 is good :)
