### ISSUE TITLE
Does it work with 1.16? (OCT 17 release)

### ISSUE THREAD

**Issue by kobocha** [gurrgur/er-patcher#84]
When I try to run ER with the patcher I only get a command prompt window popup and close down and ER goes from "launching" in steam and back to "Play".  And obviously the game refuses to launch.

Maybe it just doesn't work for the current version?

ps. tried using:
python er-patcher --rate 144 -uvca -- env WINE_FULLSCREEN_FSR=1 MANGOHUD=1 MANGOHUD_CONFIG=histogram %command%

and:
python er-patcher  --rate 120 --ultrawide --disable-vignette --increase-animation-distance --skip-intro -- %command%

**Comment by gurrgur** [comment]
1.16 is supported and it should work. Try copy pasting a cmd from readme, check your python version and check that you have the latest version of er-patcher.

**Comment by kobocha** [comment]
Ok weird. I'll try a completely fresh install and copying from the readme. Maybe it's the python version? Does it need to be exactly 3.8 or 3.8 and above?

**Comment by kobocha** [comment]
Getting the same issue with fresh install. I'm on win11 and I'm using python er-patcher --all --rate 30 --disable-rune-loss -- %command% for launch parameters through steam.

ps. Does it matter that I'm running two screens maybe? both on displayport but differing resolutions (2560x1440 and 3440x1440)

**Comment by kobocha** [comment]
With a bit of tinkering and help from a friend I have now found the issue. I hadn't installed python with "add to path" option installed. It now seems to work properly :D!
