### ISSUE TITLE
Running with EAC 

### ISSUE THREAD

**Issue by IDeathByte** [gurrgur/er-patcher#9]
it possible to run pacther without EAC disabling?
I understand risks, and on 1.02 i used fix ultrawide/vignette and animations by hex without blocking

**Comment by gurrgur** [comment]
Hi, I'm not planning to support this but you can try following these steps:

1. Open er-patcher in a text editor and change the last two lines to

``` python
    # os.remove(patched_exe_dir / exe_name)
    # os.rmdir(patched_exe_dir)
```

2. Set the launch options you want to run the game with (assuming everything works) and start it from steam once (we expect it to crash here)
3. rename the original `eldenring.exe` to `eldenring.exe.bak`
4. move the patched `./er-patcher-tmp/eldenring.exe` to the main game directory
5. remove all Elden Ring launch options in steam
6. start the game from steam

**Comment by IDeathByte** [comment]
That works. Thanks

**Comment by gurrgur** [comment]
Hey there, we have added a new flag that allows enabling EAC so I'll be closing this issue ;)
